# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: spot-schedule-scrap

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        python -m pip install selenium
        python -m pip install openpyxl
        python -m pip install requests
    - name: Install ubuntu packages
      run: |
        sudo apt-get install fonts-unfonts-core
        sudo apt-get install fonts-unfonts-extra
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add        
        sudo apt-get install google-chrome-stable    
    - name: run
      run: |
        python ./game_crawling.py
    - name: commit
      run: |
        git config --local user.email "20152917@sungshin.ac.kr"
        git config --local user.name "2yeseul"
        git add .
        git commit -m "2022 baseball schedules"
        git pull origin master
    - name: push
      uses: ad-m/github-push-action@master
      with:
        branch: 'master'
        github_token: $ 
  
